import express from "express";
import cors from "cors";
import path from "path";
import { fileURLToPath } from "url";
import { createAtcSession, getAtcSession, handlePilotTransmission, ingestTelemetry, getEngineHealth } from "./src/core/skyEchoAtcEngine.js";
import { parseSimBriefLikeRoute } from "./src/core/routeTools.js";
import { getVolantaHealth, startVolantaSession, stopVolantaSession, getVolantaSession, ingestVolantaTelemetry, buildVolantaSnapshot } from "./src/connectors/volantaBridge.js";
import { buildSayIntentionsPayload, sendToSayIntentionsIfEnabled } from "./src/connectors/sayIntentionsAdapter.js";
const app=express();app.use(cors());app.use(express.json({limit:"4mb"}));app.use(express.text({limit:"2mb",type:["text/*","application/octet-stream"]}));
const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);const PORT=process.env.PORT||10000;const FS2EFB_URL=process.env.FS2EFB_URL||process.env.FS2EFB_ENDPOINT||"";const SIMBRIEF_USER_ID=process.env.SIMBRIEF_USER_ID||process.env.SIMBRIEF_PILOT_ID||"";const VOLANTA_MODE=process.env.VOLANTA_MODE||"standby";const VOLANTA_WEBHOOK_URL=process.env.VOLANTA_WEBHOOK_URL||"";const VOLANTA_API_URL=process.env.VOLANTA_API_URL||"";const VOLANTA_API_KEY=process.env.VOLANTA_API_KEY||"";const SAYINTENTIONS_ADAPTER_ENABLED=/^true$/i.test(process.env.SAYINTENTIONS_ADAPTER_ENABLED||"false");const SAYINTENTIONS_SIMAPI_URL=process.env.SAYINTENTIONS_SIMAPI_URL||"";const SAYINTENTIONS_API_KEY=process.env.SAYINTENTIONS_API_KEY||"";
const runtime={fs2efb:{lastPoll:null,lastIngest:null,lastError:null,lastData:null},lastSayIntentionsForward:null};
app.use("/frontend",express.static(path.join(__dirname,"frontend")));app.use("/public",express.static(path.join(__dirname,"public")));app.use("/assets",express.static(path.join(__dirname,"assets")));
function safeJson(text){try{return JSON.parse(text)}catch{return{raw:text}}}function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function normalizeFs2EfbTelemetry(raw={}){const src=raw?.aircraft||raw?.telemetry||raw?.data||raw?.state||raw||{};const pos=src.position||src.pos||raw.position||{};return{source:"fs2efb",timestamp:new Date().toISOString(),callsign:src.callsign||src.callSign||src.flight||src.atc_id||raw.callsign||"",latitude:num(src.lat??src.latitude??pos.lat??pos.latitude),longitude:num(src.lon??src.lng??src.longitude??pos.lon??pos.lng??pos.longitude),altitude:num(src.altitude??src.alt??src.baro_altitude??pos.altitude),heading:num(src.heading??src.hdg??src.track),groundSpeed:num(src.groundSpeed??src.groundspeed??src.gs??src.speed),indicatedAirspeed:num(src.ias??src.indicatedAirspeed),verticalSpeed:num(src.verticalSpeed??src.vs??src.vertical_speed),onGround:Boolean(src.onGround??src.simOnGround??src.ground),com1:src.com1??src.com1Active??src.radio??src.frequency??null,transponder:src.squawk??src.transponder??null,raw};}
async function handleTelemetry(telemetry){runtime.fs2efb.lastData=telemetry;runtime.fs2efb.lastError=null;const engine=ingestTelemetry(telemetry);const volanta=await ingestVolantaTelemetry(telemetry,{mode:VOLANTA_MODE,webhookUrl:VOLANTA_WEBHOOK_URL,apiUrl:VOLANTA_API_URL,apiKey:VOLANTA_API_KEY});const si=await sendToSayIntentionsIfEnabled(buildSayIntentionsPayload(telemetry,getAtcSession()),{enabled:SAYINTENTIONS_ADAPTER_ENABLED,url:SAYINTENTIONS_SIMAPI_URL,apiKey:SAYINTENTIONS_API_KEY});runtime.lastSayIntentionsForward=si;return{engine,volanta,sayIntentions:si};}
async function pollFs2Efb(){if(!FS2EFB_URL)return{ok:false,error:"FS2EFB_URL/FS2EFB_ENDPOINT not configured."};try{const r=await fetch(FS2EFB_URL,{cache:"no-store"});const telemetry=normalizeFs2EfbTelemetry(safeJson(await r.text()));runtime.fs2efb.lastPoll=new Date().toISOString();const result=await handleTelemetry(telemetry);return{ok:true,telemetry,...result};}catch(e){runtime.fs2efb.lastError=e.message;return{ok:false,error:e.message};}}
app.get("/",(req,res)=>res.json({ok:true,service:"SkyEchoCabin Core Engine",version:"6.9.57",app:"/app/"}));
app.get(["/app","/app/"],(req,res)=>res.sendFile(path.join(__dirname,"frontend","index.html")));
app.get("/health",(req,res)=>res.json({ok:true,version:"6.9.57",architecture:"FS2EFB + SimBrief + procedure data + protected ATC state machine + parser + phraseology + optional Volanta/SayIntentions adapters",fs2efbConfigured:Boolean(FS2EFB_URL),simbriefConfigured:Boolean(SIMBRIEF_USER_ID),volantaMode:VOLANTA_MODE,sayIntentionsAdapterEnabled:SAYINTENTIONS_ADAPTER_ENABLED,engine:getEngineHealth()}));
app.post("/api/session/start",(req,res)=>{const f=req.body||{};const session=createAtcSession({callsign:f.callsign||f.flightNumber||"AAL318",aircraft:f.aircraft||f.aircraftType||"B738",origin:f.origin||f.departure||"",destination:f.destination||f.dest||"",route:f.route||"",cruiseAltitude:f.cruiseAltitude||f.cruise||"",simbriefId:f.simbriefId||SIMBRIEF_USER_ID||"",runway:f.runway||""});startVolantaSession(f);res.json({ok:true,session});});
app.get("/api/session",(req,res)=>res.json({ok:true,session:getAtcSession()}));
app.post("/api/pilot/transmit",(req,res)=>{const text=req.body?.text||req.body?.transcript||"";res.json({ok:true,...handlePilotTransmission(text,{telemetry:runtime.fs2efb.lastData})});});
app.post("/api/route/parse",(req,res)=>res.json({ok:true,parsed:parseSimBriefLikeRoute(req.body?.route||req.body?.text||"")}));
app.get("/api/fs2efb",async(req,res)=>{const result=await pollFs2Efb();res.status(result.ok?200:502).json(result)});
app.post("/api/fs2efb/ingest",async(req,res)=>{const raw=typeof req.body==="string"?safeJson(req.body):req.body;const telemetry=normalizeFs2EfbTelemetry(raw);runtime.fs2efb.lastIngest=new Date().toISOString();const result=await handleTelemetry(telemetry);res.json({ok:true,telemetry,...result});});
app.get("/api/telemetry/state",async(req,res)=>{if(!runtime.fs2efb.lastData&&FS2EFB_URL)await pollFs2Efb();res.json({ok:true,source:"fs2efb",lastPoll:runtime.fs2efb.lastPoll,lastIngest:runtime.fs2efb.lastIngest,lastError:runtime.fs2efb.lastError,telemetry:runtime.fs2efb.lastData,engine:getAtcSession()});});
app.get("/volanta/health",(req,res)=>res.json(getVolantaHealth({mode:VOLANTA_MODE,webhookUrl:VOLANTA_WEBHOOK_URL,apiUrl:VOLANTA_API_URL,apiKeyConfigured:Boolean(VOLANTA_API_KEY),fs2efbConfigured:Boolean(FS2EFB_URL)})));app.post("/volanta/session/start",(req,res)=>res.json({ok:true,session:startVolantaSession(req.body||{})}));app.post("/volanta/session/stop",(req,res)=>res.json({ok:true,session:stopVolantaSession(req.body||{})}));app.get("/volanta/session",(req,res)=>res.json({ok:true,session:getVolantaSession()}));app.get("/volanta/snapshot",(req,res)=>res.json({ok:true,snapshot:buildVolantaSnapshot(runtime.fs2efb.lastData)}));
app.get("/sayintentions/adapter/health",(req,res)=>res.json({ok:true,enabled:SAYINTENTIONS_ADAPTER_ENABLED,configured:Boolean(SAYINTENTIONS_SIMAPI_URL),lastForward:runtime.lastSayIntentionsForward}));
app.get("/traffic-v2/health",(req,res)=>res.json({ok:true,service:"traffic-v2",version:"6.9.57",source:"skyecho-core-engine",fs2efbConfigured:Boolean(FS2EFB_URL),lastTelemetryPoll:runtime.fs2efb.lastPoll,lastTelemetryIngest:runtime.fs2efb.lastIngest,engine:getEngineHealth()}));
app.get("/traffic-v2/state",async(req,res)=>{if(!runtime.fs2efb.lastData&&FS2EFB_URL)await pollFs2Efb();res.json({ok:true,source:"skyecho-core-engine",aircraftCount:runtime.fs2efb.lastData?1:0,aircraft:runtime.fs2efb.lastData?[runtime.fs2efb.lastData]:[],engine:getAtcSession(),lastError:runtime.fs2efb.lastError});});
app.post("/traffic-v2/start",async(req,res)=>{if(!getAtcSession().active||req.body?.route){createAtcSession({callsign:req.body?.callsign||"AAL318",aircraft:req.body?.aircraft||"B738",origin:req.body?.origin||req.body?.airport||"",destination:req.body?.dest||req.body?.destination||"",route:req.body?.route||"",cruiseAltitude:req.body?.cruiseAltitude||"",runway:req.body?.runway||""});}if(FS2EFB_URL)await pollFs2Efb();res.json({ok:true,running:true,source:"skyecho-core-engine",aircraftCount:runtime.fs2efb.lastData?1:0,radio:req.body?.userFrequency||runtime.fs2efb.lastData?.com1||null,engine:getAtcSession()});});
app.post("/traffic-v2/stop",(req,res)=>res.json({ok:true,running:false}));app.use((req,res)=>res.status(404).json({ok:false,error:`Cannot ${req.method} ${req.path}`}));app.listen(PORT,()=>console.log(`SkyEchoCabin Core Engine v6.9.57 on ${PORT}`));
