const state={active:false,sessionId:null,startedAt:null,stoppedAt:null,flight:null,lastTelemetry:null,lastSnapshot:null,lastForward:null,lastError:null,history:[]};
const now=()=>new Date().toISOString();const id=()=>`skyecho-volanta-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;
function phaseHint(t={}){if(!t)return"unknown";if(t.onGround&&(!t.groundSpeed||t.groundSpeed<5))return"parked";if(t.onGround)return"taxi";if(t.altitude<3000)return"departure_or_final";if(t.altitude<18000)return"climb_or_descent";return"enroute";}
export function getVolantaHealth(config={}){return{ok:true,service:"skyecho-volanta-bridge",version:"6.9.57",mode:config.mode||"standby",officialVolantaApiClaim:false,activeSession:state.active,lastError:state.lastError};}
export function startVolantaSession(flight={}){state.active=true;state.sessionId=state.sessionId||id();state.startedAt=state.startedAt||now();state.stoppedAt=null;state.flight=flight;state.history.push({type:"start",timestamp:now(),flight});return getVolantaSession();}
export function stopVolantaSession(payload={}){state.active=false;state.stoppedAt=now();state.history.push({type:"stop",timestamp:now(),payload});return getVolantaSession();}
export function getVolantaSession(){return{...state,historyCount:state.history.length,history:undefined};}
export function buildVolantaSnapshot(telemetry=null){const snapshot={sessionId:state.sessionId,active:state.active,timestamp:now(),flight:state.flight,telemetry,phaseHint:phaseHint(telemetry),loggable:Boolean(state.active&&telemetry?.latitude!=null&&telemetry?.longitude!=null)};state.lastSnapshot=snapshot;return snapshot;}
export async function ingestVolantaTelemetry(telemetry={},config={}){state.lastTelemetry=telemetry;const snapshot=buildVolantaSnapshot(telemetry);state.history.push({type:"telemetry",timestamp:now(),telemetry});if(!state.active)return{forwarded:false,reason:"no_active_session",snapshot};if(config.mode==="webhook"&&config.webhookUrl){try{const r=await fetch(config.webhookUrl,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(snapshot)});state.lastForward={timestamp:now(),mode:"webhook",status:r.status};return{forwarded:r.ok,status:r.status,snapshot};}catch(e){state.lastError=e.message;return{forwarded:false,error:e.message,snapshot};}}return{forwarded:false,reason:"standby_or_local_mode",snapshot};}
