import { isSpeedLevelToken, isFixToken } from "./routeTools.js";
export function spokenCallsign(callsign="") { const c=String(callsign||"Aircraft").toUpperCase(); if(c.startsWith("UAL"))return "United "+c.slice(3).split("").join(" "); if(c.startsWith("AAL"))return "American "+c.slice(3).split("").join(" "); if(c.startsWith("DAL"))return "Delta "+c.slice(3).split("").join(" "); return c; }
export function cleanPhrase(text="") { return String(text||"").replace(/\b(?:N\d{4}F\d{1,3}|K\d{4}F\d{1,3}|M\d{3}F\d{1,3}|F\d{2,3}|FL\d{2,3})\b/g,"").replace(/\b(proceed\s+)?direct\s*(?:\.|,|$)/gi,"").replace(/\s+,/g,",").replace(/\s+\./g,".").replace(/\s{2,}/g," ").trim(); }
export function buildResponse(session, intentResult, options={}) {
  const cs=spokenCallsign(session.callsign); const phase=session.phase; const tokens=intentResult.tokens; let text=`${cs}, roger.`; let expectedReadback=[];
  if(intentResult.intent==="request_clearance"){const sid=session.departureProcedure||"departure";const cruise=session.cruiseAltitude||"filed altitude"; text=`${cs}, cleared to ${session.destination||"destination"} via the ${sid}, then as filed. Climb via SID. Expect ${cruise} ten minutes after departure. Departure frequency 119.45. Squawk 5132.`; expectedReadback=[sid,cruise,"119.45","5132"];}
  else if(intentResult.intent==="request_push_start"){text=`${cs}, push and start approved.`;expectedReadback=["push","start"];}
  else if(intentResult.intent==="request_taxi"){const r=options.runway||session.assignedRunway||"07"; text=`${cs}, taxi to runway ${r} via assigned taxiways. Hold short runway ${r}.`; expectedReadback=[r,"hold short"];}
  else if(intentResult.intent==="ready_departure"){const r=options.runway||session.assignedRunway||"07"; text=`${cs}, runway ${r}, cleared for takeoff. Wind calm.`; expectedReadback=[r,"cleared for takeoff"];}
  else if(intentResult.intent==="frequency_checkin"){ if(["departure","climb"].includes(phase)){const alt=session.nextAltitude||"15000";const next=session.routeFixes.find(x=>isFixToken(x)&&!isSpeedLevelToken(x)); text=next?`${cs}, radar contact. Climb and maintain ${alt}, proceed direct ${next}.`:`${cs}, radar contact. Climb and maintain ${alt}.`; expectedReadback=[String(alt)];} else if(["enroute","center"].includes(phase)){text=`${cs}, radar contact. Maintain present altitude.`;} else if(phase==="arrival"){text=`${cs}, radar contact. Descend via the published arrival. Expect further descent shortly.`; expectedReadback=["descend via arrival"];} else if(phase==="approach"){text=`${cs}, radar contact. Continue approach.`;} else text=`${cs}, radar contact.`; }
  else if(intentResult.intent==="arrival_checkin"){text=`${cs}, radar contact. Descend via the published arrival. Expect further descent shortly.`; expectedReadback=["descend via arrival"];}
  else if(intentResult.intent==="route_position_report"){const rep=tokens.routeTokens[0]||"that point";const next=session.arrivalProcedure||session.approachFix||"next reporting point"; text=`${cs}, roger, ${rep} copied. Continue present course, report ${next}.`;}
  else if(intentResult.intent==="ride_request"){text=`${cs}, ride reports show smoother air one level higher. Advise if requesting higher.`;}
  else if(intentResult.intent==="weather_deviation_request"){text=`${cs}, deviation approved as requested. When clear of weather, proceed direct ${session.nextFix||session.routeFixes[0]||"next fix"}.`;expectedReadback=["deviation approved"];}
  else if(intentResult.intent==="approach_established"){const r=tokens.runway||session.assignedRunway||"07"; text=`${cs}, runway ${r}, cleared to land. Wind zero eight zero at one six, gusts two two.`; expectedReadback=[r,"cleared to land"];}
  else if(intentResult.intent==="instruction_readback"){text=`${cs}, readback correct.`;}
  return {text:cleanPhrase(text),expectedReadback:expectedReadback.filter(x=>x&&!isSpeedLevelToken(x))};
}
