import { parseSimBriefLikeRoute, isSpeedLevelToken } from "./routeTools.js";
import { classifyIntent } from "./intentParser.js";
import { buildResponse } from "./phraseologyEngine.js";
import { routeContainsArrival, routeContainsDeparture } from "../data/procedures.js";
const PHASE_RANK={preflight:0,clearance:1,ground:2,tower:3,departure:4,climb:5,enroute:6,center:6,arrival:7,approach:8,tower_arrival:9,ground_arrival:10,complete:11};
let session=null; const now=()=>new Date().toISOString(); const rank=p=>PHASE_RANK[p]??0;
function safeSetPhase(current,next,reason=""){return rank(next)<rank(current)?{phase:current,blocked:{from:current,to:next,reason}}:{phase:next,blocked:null};}
function inferPhaseFromTelemetry(t,cur){if(!t)return cur;const alt=Number(t.altitude??0),gs=Number(t.groundSpeed??0),g=Boolean(t.onGround); if(g&&gs<5&&rank(cur)<rank("ground"))return"ground"; if(g&&gs>=5&&rank(cur)<rank("tower"))return"ground"; if(!g&&alt<3000&&rank(cur)<rank("departure"))return"departure"; if(!g&&alt>=3000&&alt<18000&&rank(cur)<rank("climb"))return"climb"; if(!g&&alt>=18000&&rank(cur)<rank("enroute"))return"enroute"; return cur;}
function inferPhaseFromIntent(ir,cur){const intent=ir.intent;if(intent==="request_clearance")return"clearance"; if(intent==="request_push_start"||intent==="request_taxi")return"ground"; if(intent==="ready_departure")return"tower"; if(intent==="arrival_checkin")return"arrival"; if(intent==="approach_established")return"approach"; if(intent==="frequency_checkin"){const txt=ir.text;if(/\b(descending|arrival|star|descent|request descent)\b/i.test(txt))return"arrival"; if(/\b(level|maintaining|fl\d{2,3}|center)\b/i.test(txt)&&rank(cur)>=rank("enroute"))return cur;} return cur;}
export function createAtcSession(flight={}){const parsed=parseSimBriefLikeRoute(flight.route||"");const origin=String(flight.origin||"").toUpperCase();const destination=String(flight.destination||"").toUpperCase();const departureProcedure=routeContainsDeparture(parsed.tokens,origin)||parsed.procedures[0]||"";const arrivalProcedure=routeContainsArrival(parsed.tokens,destination)||parsed.procedures.find(x=>x!==departureProcedure)||"";session={active:true,id:`skyecho-core-${Date.now()}`,createdAt:now(),callsign:flight.callsign||"AAL318",aircraft:flight.aircraft||"B738",origin,destination,routeRaw:flight.route||"",routeTokens:parsed.tokens,routeFixes:parsed.fixes.filter(x=>!isSpeedLevelToken(x)),routeAirways:parsed.airways,procedures:parsed.procedures,departureProcedure,arrivalProcedure,cruiseAltitude:flight.cruiseAltitude||"",phase:"preflight",assignedRunway:flight.runway||"",nextAltitude:"15000",expectedReadback:[],telemetry:null,phaseGuardBlocked:null,lastIntent:null,lastPilotTransmission:null,lastAtcTransmission:null,history:[]};return session;}
export function getAtcSession(){if(!session)return createAtcSession({});return session;}
export function ingestTelemetry(telemetry={}){const s=getAtcSession();s.telemetry=telemetry;const inferred=inferPhaseFromTelemetry(telemetry,s.phase);const guarded=safeSetPhase(s.phase,inferred,"telemetry");s.phase=guarded.phase;s.phaseGuardBlocked=guarded.blocked;s.history.push({type:"telemetry",timestamp:now(),phase:s.phase,telemetry});return{phase:s.phase,phaseGuardBlocked:s.phaseGuardBlocked};}
export function handlePilotTransmission(text="",options={}){const s=getAtcSession();if(options.telemetry)ingestTelemetry(options.telemetry);const ir=classifyIntent(text,{callsign:s.callsign,route:s.routeTokens});let next=inferPhaseFromIntent(ir,s.phase);if(/\b(descending|arrival|star|request descent|descent|chsly7|anu1)\b/i.test(text))next="arrival";const guarded=safeSetPhase(s.phase,next,"pilot intent");s.phase=guarded.phase;s.phaseGuardBlocked=guarded.blocked;const response=buildResponse(s,ir,{});s.expectedReadback=response.expectedReadback.filter(x=>x&&!isSpeedLevelToken(x));s.lastIntent=ir.intent;s.lastPilotTransmission=text;s.lastAtcTransmission=response.text;s.history.push({type:"pilot_atc_exchange",timestamp:now(),phase:s.phase,intent:ir.intent,pilot:text,atc:response.text,expectedReadback:s.expectedReadback,phaseGuardBlocked:s.phaseGuardBlocked});return{session:s,phase:s.phase,intent:ir.intent,tokens:ir.tokens,atcText:response.text,expectedReadback:s.expectedReadback,phaseGuardBlocked:s.phaseGuardBlocked};}
export function getEngineHealth(){const s=getAtcSession();return{active:s.active,sessionId:s.id,phase:s.phase,callsign:s.callsign,routeTokens:s.routeTokens,expectedReadback:s.expectedReadback,lastIntent:s.lastIntent,lastAtcTransmission:s.lastAtcTransmission,historyCount:s.history.length};}
